package net.codinux.invoicing.model.codes

enum class ChargeReasonCode(val code: String, val meaning: String, val description: String, val isFrequentlyUsedValue: Boolean) {
	AA("AA", "Advertising", "The service of providing advertising.", true),
	AAA("AAA", "Telecommunication", "The service of providing telecommunication activities and/or faclities.", false),
	AAC("AAC", "Technical modification", "The service of making technical modifications to a product.", false),
	AAD("AAD", "Job-order production", "The service of producing to order.", false),
	AAE("AAE", "Outlays", "The service of providing money for outlays on behalf of a trading partner.", false),
	AAF("AAF", "Off-premises", "The service of providing services outside the premises of the provider.", false),
	AAH("AAH", "Additional processing", "The service of providing additional processing.", false),
	AAI("AAI", "Attesting", "The service of certifying validity.", false),
	AAS("AAS", "Acceptance", "The service of accepting goods or services.", false),
	AAT("AAT", "Rush delivery", "The service to provide a rush delivery.", false),
	AAV("AAV", "Special construction", "The service of providing special construction.", false),
	AAY("AAY", "Airport facilities", "The service of providing airport facilities.", false),
	AAZ("AAZ", "Concession", "The service allowing a party to use another party's facilities.", false),
	ABA("ABA", "Compulsory storage", "The service provided to hold a compulsory inventory.", false),
	ABB("ABB", "Fuel removal", "Remove or off-load fuel from vehicle, vessel or craft.", false),
	ABC("ABC", "Into plane", "Service of delivering goods to an aircraft from local storage.", false),
	ABD("ABD", "Overtime", "The service of providing labour beyond the established limit of working hours.", false),
	ABF("ABF", "Tooling", "The service of providing specific tooling.", false),
	ABK("ABK", "Miscellaneous", "Miscellaneous services.", false),
	ABL("ABL", "Additional packaging", "The service of providing additional packaging.", true),
	ABN("ABN", "Dunnage", "The service of providing additional padding materials required to secure and protect a cargo within a shipping container.", false),
	ABR("ABR", "Containerisation", "The service of packing items into a container.", false),
	ABS("ABS", "Carton packing", "The service of packing items into a carton.", false),
	ABT("ABT", "Hessian wrapped", "The service of hessian wrapping.", false),
	ABU("ABU", "Polyethylene wrap packing", "The service of packing in polyethylene wrapping.", false),
	ACF("ACF", "Miscellaneous treatment", "Miscellaneous treatment service.", false),
	ACG("ACG", "Enamelling treatment", "The service of providing enamelling treatment.", false),
	ACH("ACH", "Heat treatment", "The service of treating with heat.", false),
	ACI("ACI", "Plating treatment", "The service of providing plating treatment.", false),
	ACJ("ACJ", "Painting", "The service of painting.", false),
	ACK("ACK", "Polishing", "The service of polishing.", false),
	ACL("ACL", "Priming", "The service of priming.", false),
	ACM("ACM", "Preservation treatment", "The service of preservation treatment.", false),
	ACS("ACS", "Fitting", "Fitting service.", false),
	ADC("ADC", "Consolidation", "The service of consolidating multiple consignments into one shipment.", false),
	ADE("ADE", "Bill of lading", "The service of providing a bill of lading document.", false),
	ADJ("ADJ", "Airbag", "The service of surrounding a product with an air bag.", false),
	ADK("ADK", "Transfer", "The service of transferring.", false),
	ADL("ADL", "Slipsheet", "The service of securing a stack of products on a slipsheet.", false),
	ADM("ADM", "Binding", "Binding service.", false),
	ADN("ADN", "Repair or replacement of broken returnable package", "The service of repairing or replacing a broken returnable package.", false),
	ADO("ADO", "Efficient logistics", "A code indicating efficient logistics services.", false),
	ADP("ADP", "Merchandising", "A code indicating that merchandising services are in operation.", false),
	ADQ("ADQ", "Product mix", "A code indicating that product mixing services are in operation.", false),
	ADR("ADR", "Other services", "A code indicating that other non-specific services are in operation.", true),
	ADT("ADT", "Pick-up", "The service of picking up or collection of goods.", true),
	ADW("ADW", "Chronic illness", "The special services provided due to chronic illness.", false),
	ADY("ADY", "New product introduction", "A service provided by a buyer when introducing a new product from a suppliers range to the range traded by the buyer.", false),
	ADZ("ADZ", "Direct delivery", "Direct delivery service.", false),
	AEA("AEA", "Diversion", "The service of diverting deliverables.", false),
	AEB("AEB", "Disconnect", "The service is a disconnection.", false),
	AEC("AEC", "Distribution", "Distribution service.", false),
	AED("AED", "Handling of hazardous cargo", "A service for handling hazardous cargo.", false),
	AEF("AEF", "Rents and leases", "The service of renting and/or leasing.", false),
	AEH("AEH", "Location differential", "Delivery to a different location than previously contracted.", false),
	AEI("AEI", "Aircraft refueling", "Fuel being put into the aircraft.", false),
	AEJ("AEJ", "Fuel shipped into storage", "Fuel being shipped into a storage system.", false),
	AEK("AEK", "Cash on delivery", "The provision of a cash on delivery (COD) service.", false),
	AEL("AEL", "Small order processing service", "A service related to the processing of small orders.", false),
	AEM("AEM", "Clerical or administrative services", "The provision of clerical or administrative services.", false),
	AEN("AEN", "Guarantee", "The service of providing a guarantee.", false),
	AEO("AEO", "Collection and recycling", "The service of collection and recycling products.", false),
	AEP("AEP", "Copyright fee collection", "The service of collecting copyright fees.", false),
	AES("AES", "Veterinary inspection service", "The service of providing veterinary inspection.", false),
	AET("AET", "Pensioner service", "Special service when the subject is a pensioner.", false),
	AEU("AEU", "Medicine free pass holder", "Special service when the subject holds a medicine free pass.", false),
	AEV("AEV", "Environmental protection service", "The provision of an environmental protection service.", false),
	AEW("AEW", "Environmental clean-up service", "The provision of an environmental clean-up service.", false),
	AEX("AEX", "National cheque processing service outside account area", "Service of processing a national cheque outside the ordering customer's bank trading area.", false),
	AEY("AEY", "National payment service outside account area", "Service of processing a national payment to a beneficiary holding an account outside the trading area of the ordering customer's bank.", false),
	AEZ("AEZ", "National payment service within account area", "Service of processing a national payment to a beneficiary holding an account within the trading area of the ordering customer's bank.", false),
	AJ("AJ", "Adjustments", "The service of making adjustments.", false),
	AU("AU", "Authentication", "The service of authenticating.", false),
	CA("CA", "Cataloguing", "The provision of cataloguing services.", false),
	CAB("CAB", "Cartage", "Movement of goods by heavy duty cart or vehicle.", false),
	CAD("CAD", "Certification", "The service of certifying.", false),
	CAE("CAE", "Certificate of conformance", "The service of providing a certificate of conformance.", false),
	CAF("CAF", "Certificate of origin", "The service of providing a certificate of origin.", false),
	CAI("CAI", "Cutting", "The service of cutting.", false),
	CAJ("CAJ", "Consular service", "The service provided by consulates.", false),
	CAK("CAK", "Customer collection", "The service of collecting goods by the customer.", false),
	CAL("CAL", "Payroll payment service", "Provision of a payroll payment service.", false),
	CAM("CAM", "Cash transportation", "Provision of a cash transportation service.", false),
	CAN("CAN", "Home banking service", "Provision of a home banking service.", false),
	CAO("CAO", "Bilateral agreement service", "Provision of a service as specified in a bilateral special agreement.", false),
	CAP("CAP", "Insurance brokerage service", "Provision of an insurance brokerage service.", false),
	CAQ("CAQ", "Cheque generation", "Provision of a cheque generation service.", false),
	CAR("CAR", "Preferential merchandising location", "Service of assigning a preferential location for merchandising.", false),
	CAS("CAS", "Crane", "The service of providing a crane.", false),
	CAT("CAT", "Special colour service", "Providing a colour which is different from the default colour.", false),
	CAU("CAU", "Sorting", "The provision of sorting services.", false),
	CAV("CAV", "Battery collection and recycling", "The service of collecting and recycling batteries.", false),
	CAW("CAW", "Product take back fee", "The fee the consumer must pay the manufacturer to take back the product.", false),
	CAX("CAX", "Quality control released", "Informs the stockholder it is free to distribute the quality controlled passed goods.", false),
	CAY("CAY", "Quality control held", "Instructs the stockholder to withhold distribution of the goods until the manufacturer has completed a quality control assessment.", false),
	CAZ("CAZ", "Quality control embargo", "Instructs the stockholder to withhold distribution of goods which have failed quality control tests.", false),
	CD("CD", "Car loading", "Car loading service.", false),
	CG("CG", "Cleaning", "Cleaning service.", false),
	CS("CS", "Cigarette stamping", "The service of providing cigarette stamping.", false),
	CT("CT", "Count and recount", "The service of doing a count and recount.", false),
	DAB("DAB", "Layout/design", "The service of providing layout/design.", false),
	DAC("DAC", "Assortment allowance", "Allowance given when a specific part of a suppliers assortment is purchased by the buyer.", false),
	DAD("DAD", "Driver assigned unloading", "The service of unloading by the driver.", false),
	DAF("DAF", "Debtor bound", "A special allowance or charge applicable to a specific debtor.", false),
	DAG("DAG", "Dealer allowance", "An allowance offered by a party dealing a certain brand or brands of products.", false),
	DAH("DAH", "Allowance transferable to the consumer", "An allowance given by the manufacturer which should be transfered to the consumer.", false),
	DAI("DAI", "Growth of business", "An allowance or charge related to the growth of business over a pre-determined period of time.", false),
	DAJ("DAJ", "Introduction allowance", "An allowance related to the introduction of a new product to the range of products traded by a retailer.", false),
	DAK("DAK", "Multi-buy promotion", "A code indicating special conditions related to a multi- buy promotion.", false),
	DAL("DAL", "Partnership", "An allowance or charge related to the establishment and on-going maintenance of a partnership.", false),
	DAM("DAM", "Return handling", "An allowance or change related to the handling of returns.", false),
	DAN("DAN", "Minimum order not fulfilled charge", "Charge levied because the minimum order quantity could not be fulfilled.", false),
	DAO("DAO", "Point of sales threshold allowance", "Allowance for reaching or exceeding an agreed sales threshold at the point of sales.", false),
	DAP("DAP", "Wholesaling discount", "A special discount related to the purchase of products through a wholesaler.", false),
	DAQ("DAQ", "Documentary credits transfer commission", "Fee for the transfer of transferable documentary credits.", false),
	DL("DL", "Delivery", "The service of providing delivery.", false),
	EG("EG", "Engraving", "The service of providing engraving.", false),
	EP("EP", "Expediting", "The service of expediting.", false),
	ER("ER", "Exchange rate guarantee", "The service of guaranteeing exchange rate.", false),
	FAA("FAA", "Fabrication", "The service of providing fabrication.", false),
	FAB("FAB", "Freight equalization", "The service of load balancing.", false),
	FAC("FAC", "Freight extraordinary handling", "The service of providing freight's extraordinary handling.", false),
	FC("FC", "Freight service", "The service of moving goods, by whatever means, from one place to another.", true),
	FH("FH", "Filling/handling", "The service of providing filling/handling.", false),
	FI("FI", "Financing", "The service of providing financing.", true),
	GAA("GAA", "Grinding", "The service of grinding.", false),
	HAA("HAA", "Hose", "The service of providing a hose.", false),
	HD("HD", "Handling", "Handling service.", false),
	HH("HH", "Hoisting and hauling", "The service of hoisting and hauling.", false),
	IAA("IAA", "Installation", "The service of installing.", false),
	IAB("IAB", "Installation and warranty", "The service of installing and providing warranty.", false),
	ID("ID", "Inside delivery", "The service of providing delivery inside.", false),
	IF("IF", "Inspection", "The service of inspection.", false),
	IR("IR", "Installation and training", "The service of providing installation and training.", false),
	IS("IS", "Invoicing", "The service of providing an invoice.", false),
	KO("KO", "Koshering", "The service of preparing food in accordance with Jewish law.", false),
	L1("L1", "Carrier count", "The service of counting by the carrier.", false),
	LA("LA", "Labelling", "Labelling service.", true),
	LAA("LAA", "Labour", "The service to provide required labour.", false),
	LAB("LAB", "Repair and return", "The service of repairing and returning.", false),
	LF("LF", "Legalisation", "The service of legalising.", false),
	MAE("MAE", "Mounting", "The service of mounting.", false),
	MI("MI", "Mail invoice", "The service of mailing an invoice.", false),
	ML("ML", "Mail invoice to each location", "The service of mailing an invoice to each location.", false),
	NAA("NAA", "Non-returnable containers", "The service of providing non-returnable containers.", false),
	OA("OA", "Outside cable connectors", "The service of providing outside cable connectors.", false),
	PA("PA", "Invoice with shipment", "The service of including the invoice with the shipment.", false),
	PAA("PAA", "Phosphatizing (steel treatment)", "The service of phosphatizing the steel.", false),
	PC("PC", "Packing", "The service of packing.", false),
	PL("PL", "Palletizing", "The service of palletizing.", false),
	PRV("PRV", "Price variation", "Price variation related to energy and or raw materials cost variation.", false),
	RAB("RAB", "Repacking", "The service of repacking.", false),
	RAC("RAC", "Repair", "The service of repairing.", false),
	RAD("RAD", "Returnable container", "The service of providing returnable containers.", false),
	RAF("RAF", "Restocking", "The service of restocking.", false),
	RE("RE", "Re-delivery", "The service of re-delivering.", false),
	RF("RF", "Refurbishing", "The service of refurbishing.", false),
	RH("RH", "Rail wagon hire", "The service of providing rail wagons for hire.", false),
	RV("RV", "Loading", "The service of loading goods.", false),
	SA("SA", "Salvaging", "The service of salvaging.", false),
	SAA("SAA", "Shipping and handling", "The service of shipping and handling.", false),
	SAD("SAD", "Special packaging", "The service of special packaging.", false),
	SAE("SAE", "Stamping", "The service of stamping.", false),
	SAI("SAI", "Consignee unload", "The service of unloading by the consignee.", false),
	SG("SG", "Shrink-wrap", "The service of shrink-wrapping.", false),
	SH("SH", "Special handling", "The service of special handling.", false),
	SM("SM", "Special finish", "The service of providing a special finish.", false),
	SU("SU", "Set-up", "The service of setting-up.", false),
	TAB("TAB", "Tank renting", "The service of providing tanks for hire.", false),
	TAC("TAC", "Testing", "The service of testing.", false),
	TT("TT", "Transportation - third party billing", "The service of providing third party billing for transportation.", false),
	TV("TV", "Transportation by vendor", "The service of providing transportation by the vendor.", false),
	V1("V1", "Drop yard", "The service of delivering goods at the yard.", false),
	V2("V2", "Drop dock", "The service of delivering goods at the dock.", false),
	WH("WH", "Warehousing", "The service of storing and handling of goods in a warehouse.", false),
	XAA("XAA", "Combine all same day shipment", "The service of combining all shipments for the same day.", false),
	YY("YY", "Split pick-up", "The service of providing split pick-up.", false),
	ZZZ("ZZZ", "Mutually defined", "A code assigned within a code list to be used on an interim basis and as defined among trading partners until a precise code can be assigned to the code list.", false),
}