package net.codinux.invoicing.model.codes

enum class InvoiceType(val code: String, val meaning: String, val useFor: InvoiceTypeUseFor) {
	_71("71", "Request for payment", InvoiceTypeUseFor.Invoice),
	_80("80", "Debit note related to goods or services", InvoiceTypeUseFor.Invoice),
	_81("81", "Credit note related to goods or services", InvoiceTypeUseFor.CreditNote),
	_82("82", "Metered services invoice", InvoiceTypeUseFor.Invoice),
	_83("83", "Credit note related to financial adjustments", InvoiceTypeUseFor.CreditNote),
	_84("84", "Debit note related to financial adjustments", InvoiceTypeUseFor.Invoice),
	_102("102", "Tax notification", InvoiceTypeUseFor.Invoice),
	_130("130", "Invoicing data sheet", InvoiceTypeUseFor.Invoice),
	_202("202", "Direct payment valuation", InvoiceTypeUseFor.Invoice),
	_203("203", "Provisional payment valuation", InvoiceTypeUseFor.Invoice),
	_204("204", "Payment valuation", InvoiceTypeUseFor.Invoice),
	_211("211", "Interim application for payment", InvoiceTypeUseFor.Invoice),
	_218("218", "Final payment request based on completion of work", InvoiceTypeUseFor.Invoice),
	_219("219", "Payment request for completed units", InvoiceTypeUseFor.Invoice),
	_261("261", "Self billed credit note", InvoiceTypeUseFor.CreditNote),
	_262("262", "Consolidated credit note - goods and services", InvoiceTypeUseFor.CreditNote),
	_295("295", "Price variation invoice", InvoiceTypeUseFor.Invoice),
	_296("296", "Credit note for price variation", InvoiceTypeUseFor.CreditNote),
	_308("308", "Delcredere credit note", InvoiceTypeUseFor.CreditNote),
	_325("325", "Proforma invoice", InvoiceTypeUseFor.Invoice),
	_326("326", "Partial invoice", InvoiceTypeUseFor.Invoice),
	_331("331", "Commercial invoice which includes a packing list", InvoiceTypeUseFor.Invoice),
	_380("380", "Commercial invoice", InvoiceTypeUseFor.Invoice),
	_381("381", "Credit note", InvoiceTypeUseFor.CreditNote),
	_382("382", "Commission note", InvoiceTypeUseFor.Invoice),
	_383("383", "Debit note", InvoiceTypeUseFor.Invoice),
	_384("384", "Corrected invoice", InvoiceTypeUseFor.Invoice),
	_385("385", "Consolidated invoice", InvoiceTypeUseFor.Invoice),
	_386("386", "Prepayment invoice", InvoiceTypeUseFor.Invoice),
	_387("387", "Hire invoice", InvoiceTypeUseFor.Invoice),
	_388("388", "Tax invoice", InvoiceTypeUseFor.Invoice),
	_389("389", "Self-billed invoice", InvoiceTypeUseFor.Invoice),
	_390("390", "Delcredere invoice", InvoiceTypeUseFor.Invoice),
	_393("393", "Factored invoice", InvoiceTypeUseFor.Invoice),
	_394("394", "Lease invoice", InvoiceTypeUseFor.Invoice),
	_395("395", "Consignment invoice", InvoiceTypeUseFor.Invoice),
	_396("396", "Factored credit note", InvoiceTypeUseFor.CreditNote),
	_420("420", "Optical Character Reading (OCR) payment credit note", InvoiceTypeUseFor.CreditNote),
	_456("456", "Debit advice", InvoiceTypeUseFor.Invoice),
	_457("457", "Reversal of debit", InvoiceTypeUseFor.Invoice),
	_458("458", "Reversal of credit", InvoiceTypeUseFor.CreditNote),
	_527("527", "Self billed debit note", InvoiceTypeUseFor.Invoice),
	_532("532", "Forwarder's credit note", InvoiceTypeUseFor.CreditNote),
	_553("553", "Forwarder's invoice discrepancy report", InvoiceTypeUseFor.Invoice),
	_575("575", "Insurer's invoice", InvoiceTypeUseFor.Invoice),
	_623("623", "Forwarder's invoice", InvoiceTypeUseFor.Invoice),
	_633("633", "Port charges documents", InvoiceTypeUseFor.Invoice),
	_751("751", "Invoice information for accounting purposes", InvoiceTypeUseFor.Invoice),
	_780("780", "Freight invoice", InvoiceTypeUseFor.Invoice),
	_817("817", "Claim notification", InvoiceTypeUseFor.Invoice),
	_870("870", "Consular invoice", InvoiceTypeUseFor.Invoice),
	_875("875", "Partial construction invoice", InvoiceTypeUseFor.Invoice),
	_876("876", "Partial final construction invoice", InvoiceTypeUseFor.Invoice),
	_877("877", "Final construction invoice", InvoiceTypeUseFor.Invoice),
	_935("935", "Customs invoice", InvoiceTypeUseFor.Invoice),
}